Nandini
bluppco/captivation.agency pull request #3
Opened 2024-07-14 14:52 UTC by Nandiniverma2024

2024-07-15 04:36 UTC, tanishdotdev requested changes

2024-07-15 04:36 UTC, tanishdotdev commented on public/icons/_star_icon.svg
Rename it in lowercase separated by hyphens. star-icon.svg

2024-07-15 04:36 UTC, tanishdotdev commented on public/icons/social_icons/instagram_icon.svg
Rename it in lowercase separated by hyphens. /social-icons/instagram-icon.svg

2024-07-15 04:36 UTC, tanishdotdev commented on public/icons/social_icons/linkdin_logo.svg
Rename it in lowercase separated by hyphens.

2024-07-15 04:36 UTC, tanishdotdev commented on public/icons/social_icons/meta_icon.svg
Rename it in lowercase separated by hyphens.

2024-07-15 04:36 UTC, tanishdotdev commented on public/icons/social_icons/youtube_icon.svg
Rename it in lowercase separated by hyphens.

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/headings/four/white/index.astro
1. Add text size and weight in the path also. src/atoms/atoms-nandini/headings/four/2xl/bold/white/index.astro
2. Why there is no font?

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/headings/two/white/index.astro
Add text size and weight in the path also. src/atoms/atoms-nandini/headings/two/xl/bold/white/index.astro

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/headings/two/white/sm/index.astro
Add text size and weight in the path also and add white at the end like this. src/atoms/atoms-nandini/headings/two/sm/bold/white/index.astro

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/paragraphs/red/index.astro
1. Remove cursor default.
2. Why there is no font?

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/paragraphs/red/translate-x/index.astro
1. What is the difference between src/atoms/atoms-nandini/paragraphs/red/index.astro and this?

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/paragraphs/sm/index.astro
1. The path should be src/atoms/atoms-nandini/paragraphs/sm/white/index.astro
2. Why there is no font?

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/buttons/white/index.astro
Why there is no font?

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/buttons/transparent/index.astro
Why there is no font?

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/paragraphs/sm/italic/index.astro
Add text color in the path, src/atoms/atoms-nandini/paragraphs/sm/italic/white/index.astro

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/paragraphs/sm/white/bold/index.astro
1. Update this src/atoms/atoms-nandini/paragraphs/sm/bold/white/index.astro
2. Why there is no font?

2024-07-15 04:36 UTC, tanishdotdev commented on src/atoms/atoms-nandini/paragraphs/sm/white/index.astro
2. Why there is no font?

2024-07-15 04:36 UTC, tanishdotdev commented on src/components/home/client-testimonials/index.astro
1. In line 34 instead of gap-x-6 use gap-6.
2. In line 35, There is no height or width to the image.
3. In line 50, Use gap-x-1 instead of gap-1.
4. In line 50, Remove size-3.5 from this as it should be given to the div wrapping the individual image.
5. Loop the star icons 5 times.

2024-07-15 04:36 UTC, tanishdotdev commented on src/components/home/insights/image-card/index.astro
1. Remove col-span-1 in line 27.
2. Why have you added max-w-md in line 27?
3. In line 31, wrap the picture internal atom with a div specifying image size.

2024-07-15 04:36 UTC, tanishdotdev commented on src/components/home/insights/index.astro
Why have you not used ImageCard component for card 3?

2024-07-15 04:36 UTC, closed without merging

2024-07-15 05:18 UTC, Nandiniverma2024 commented on public/icons/_star_icon.svg
I already changed it.(will see if changes are not done yet)

2024-07-16 09:01 UTC, Nandiniverma2024 commented
done now